### ISSUE TITLE
Do you have any example/manual ?

### ISSUE THREAD

**Issue by leonardelli** [crs4/vispa#1]
Hi, I am interested in using Vispa, I downloaded it and successfully installed it, but I would need some examples about how to run it. Do you happen to have any? or a manual perhaps? because so far the only thing I managed to do was " from bl import * " into the python shell.

Thanks a lot.

**Comment by simleo** [comment]
Hi,

at the moment all we have is in the git repo, except for this [scientific paper](http://genomemedicine.com/content/6/9/67).
